"""Create task table

Revision ID: 3d4314b49bb9
Revises: 
Create Date: 2019-07-26 17:45:47.846878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4314b49bb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=125), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('done', sa.Boolean(create_constraint='done_contraint'), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
